// Writes src/font.ts from src/terrace-font.flf, the one font file the Rust
// crate also compiles in (include_str!), so both draw the same banner. The font
// is embedded rather than read at run time so the package works unchanged in a
// bundle or a `bun build --compile` executable, where no font file exists next
// to the code. `npm run build` and `npm test` regenerate it; CI fails if the
// committed copy differs.
import { readFileSync, writeFileSync } from 'node:fs'

const flf = readFileSync(new URL('../src/terrace-font.flf', import.meta.url), 'utf8')
const out =
  '// Generated by scripts/embed-font.mjs from terrace-font.flf. Do not edit.\n' +
  `export const TERRACE_FONT: string = ${JSON.stringify(flf)}\n`
writeFileSync(new URL('../src/font.ts', import.meta.url), out)
